spring.application.name=econservatoire

spring.datasource.url=jdbc:mysql://localhost:3306/e_cons_local?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alahako94@gmail.com
spring.mail.password=knzgvaentnjpltpl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

JWT-SECRET-KEY=G4dZHcMAtqKm8RdPYLn6LZ459Ugb2YVQwfkZ4ghhKav
